# BTEIntegration plugin created by Rude Yeti, Incorporated.
# A simple plugin which allows synchronization from the BuildTheEarth Website to Discord and Minecraft Servers.
# This depends on DiscordSRV, Vault, and a permissions plugin. They are a requirement for this plugin to work.

# General Configuration

# Build Team Members webpage on the BuildTheEarth Website, required to fetch the member list.
# Default value: "https://buildtheearth.net/buildteams/0/members"
build-team-members: "https://buildtheearth.net/buildteams/0/members"

# Discord Role ID, this should be the exact id of the builder role in the Discord Server.
# Default value: "000000000000000000"
discord-role-id: "000000000000000000"

# Minecraft Role Name, the precise role name of the Minecraft Server's builder role.
# Default value: "builder"
minecraft-role-name: "builder"

# If you want each time a builder is promoted to be logged to the Minecraft Server Console, enable this.
# Default value: false
log-role-changes: false