name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
depend: [DiscordSRV, Vault]
author: Rude Yeti, Incorporated
load: POSTWORLD
description: ${project.description}
commands:
  bteintegration:
    description: bteintegration