name: BTEIntegration
version: ${project.version}
main: io.github.rudeyeti.bteintegration.BTEIntegration
depend: [DiscordSRV, Vault]
author: Rude Yeti, Incorporated
load: POSTWORLD
description: A simple plugin which allows synchronization from the BuildTheEarth Website to Discord and Minecraft Servers.
commands:
  bteintegrationreload:
    description: Reloads the BTEIntegration plugin.
    usage: /bteintegrationreload
    permission: bteintegration.reload