name: BTEIntegration
version: ${project.version}
main: io.github.rudeyeti.bteintegration.BTEIntegration
depend: [DiscordSRV, Vault]
author: Rude Yeti, Incorporated
load: POSTWORLD
description: A simple plugin which allows synchronization from the BuildTheEarth Website to Discord and Minecraft Servers.
commands:
  bteintegration:
    description: The main command of the BTEIntegration Plugin.
    usage: /bteintegration <info | reload | stats>